name: Build NoGamespyVietcong

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore NoGamespyVietcong.sln

      - name: Build solution
        run: msbuild NoGamespyVietcong.sln /p:Configuration=Release /p:Platform="Any CPU"
